details:
    page_title: Tipboard exemple
layout:
    - row_1_of_2:

        - col_1_of_4:
            - tile_template: pie_chart
              tile_id: pie_chartjs_ex
              title: pie chart
              classes:

        - col_1_of_4:
            - tile_template: doughnut_chart
              tile_id: doughnut_ex
              title: doughnut
              classes:

        - col_1_of_4:
            - tile_template: polararea_chart
              tile_id: polararea_ex
              title: polar-area
              classes:

        - col_1_of_4:
            - tile_template: radar_chart
              tile_id: radar_ex
              title: radar chart
              classes:

    - row_1_of_2:

        - col_1_of_4:
            - tile_template: line_chart
              tile_id: line_chartjs_ex
              title: line tile's
              classes:

        - col_1_of_4:
            - tile_template: norm_chart
              tile_id: normjs_ex
              title: norm tile's
              classes:

        - col_1_of_4:
            - tile_template: cumulative_flow
              tile_id: cfjs_ex
              title: cumulflow
              classes:

        - col_1_of_4:
#            - tile_template: bar_chart
#              tile_id: barjs_ex
#              title: bar tile's
#              classes:

            - tile_template: vbar_chart
              tile_id: vbarjs_ex
              title: vertical bar
              classes:
